"""create initial schema

Revision ID: 0457ff04e08e
Revises: 
Create Date: 2026-10-07 04:32:48.366849

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0457ff04e08e'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('schools',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('address', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('school_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('phone', sa.String(length=30), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('role', sa.Enum('PARENT', 'SCHOOL_ADMIN', 'GATE_STAFF', name='userrole'), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['school_id'], ['schools.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('audit_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('school_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('action', sa.String(length=100), nullable=False),
    sa.Column('entity_type', sa.String(length=100), nullable=False),
    sa.Column('entity_id', sa.Integer(), nullable=True),
    sa.Column('metadata', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['school_id'], ['schools.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('pupils',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('school_id', sa.Integer(), nullable=False),
    sa.Column('parent_id', sa.Integer(), nullable=False),
    sa.Column('first_name', sa.String(length=100), nullable=False),
    sa.Column('last_name', sa.String(length=100), nullable=False),
    sa.Column('photo_url', sa.String(length=500), nullable=True),
    sa.Column('date_of_birth', sa.Date(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['parent_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['school_id'], ['schools.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('pickup_authorisations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('pupil_id', sa.Integer(), nullable=False),
    sa.Column('picker_name', sa.String(length=150), nullable=False),
    sa.Column('picker_phone', sa.String(length=30), nullable=False),
    sa.Column('relationship', sa.String(length=50), nullable=False),
    sa.Column('photo_url', sa.String(length=500), nullable=True),
    sa.Column('type', sa.String(length=50), nullable=False),
    sa.Column('starts_at', sa.DateTime(), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['pupil_id'], ['pupils.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('daily_pickup_codes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('pupil_id', sa.Integer(), nullable=False),
    sa.Column('authorisation_id', sa.Integer(), nullable=False),
    sa.Column('code_hash', sa.String(length=255), nullable=False),
    sa.Column('code_date', sa.Date(), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('used_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['authorisation_id'], ['pickup_authorisations.id'], ),
    sa.ForeignKeyConstraint(['pupil_id'], ['pupils.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('release_records',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('pupil_id', sa.Integer(), nullable=False),
    sa.Column('authorisation_id', sa.Integer(), nullable=False),
    sa.Column('verified_by', sa.Integer(), nullable=False),
    sa.Column('verification_method', sa.String(length=500), nullable=False),
    sa.Column('result', sa.String(length=500), nullable=False),
    sa.Column('released_at', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['authorisation_id'], ['pickup_authorisations.id'], ),
    sa.ForeignKeyConstraint(['pupil_id'], ['pupils.id'], ),
    sa.ForeignKeyConstraint(['verified_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('security_alerts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('school_id', sa.Integer(), nullable=False),
    sa.Column('pupil_id', sa.Integer(), nullable=True),
    sa.Column('authorisation_id', sa.Integer(), nullable=True),
    sa.Column('attempted_by', sa.Integer(), nullable=True),
    sa.Column('alert_type', sa.String(length=50), nullable=False),
    sa.Column('message', sa.String(length=500), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('resolved_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['attempted_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['authorisation_id'], ['pickup_authorisations.id'], ),
    sa.ForeignKeyConstraint(['pupil_id'], ['pupils.id'], ),
    sa.ForeignKeyConstraint(['school_id'], ['schools.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('security_alerts')
    op.drop_table('release_records')
    op.drop_table('daily_pickup_codes')
    op.drop_table('pickup_authorisations')
    op.drop_table('pupils')
    op.drop_table('audit_logs')
    op.drop_table('users')
    op.drop_table('schools')
    # ### end Alembic commands ###
